#
# Copyright (C) 2023 The Android Open Source Project
# Copyright (C) 2023 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/zechin/agpt05
BOARD_VENDOR := zechin
BOARD_DEVICE := agpt05

DEVICE_RESOLUTION := 960x480
TARGET_SCREEN_HEIGHT := 480
TARGET_SCREEN_WIDTH := 960
TARGET_BUILD_64BIT := false
TARGET_BUILD_32BIT := true
TARGET_OTA_ASSERT_DEVICE := AGP-T05
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    ro.product.model=AGP-T05 \
    ro.product.brand=AGP \
    ro.product.name=AGP-T05 \
    ro.product.device=AGP-T05 \
    ro.product.phone.model=AGP-T05 \
    ro.lxt.custom.model=AGP-T05

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_VARIANT_RUNTIME := cortex-a7
TARGET_2ND_ARCH :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_VARIANT :=
TARGET_2ND_CPU_VARIANT_RUNTIME :=
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI),$(TARGET_CPU_ABI2)
TARGET_SUPPORTS_64_BIT_APPS := false
TARGET_IS_64_BIT := false
TARGET_IS_32_BIT := true
TARGET_SUPPORTS_32_BIT_APPS := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true
TARGET_RECOVERY_FSTAB := device/zechin/agpt05/recovery/root/etc/twrp.fstab

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6580
TARGET_NO_BOOTLOADER := true
BOARD_HAS_NO_SELECT_BUTTON := true

# Display
TARGET_SCREEN_DENSITY := 240

# Boot Image
BOARD_KERNEL_CMDLINE += \
	bootopt=64S3,32S1,32S1 \
	androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x0e000000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_KERNEL_SECOND_OFFSET := 0x00f00000
BOARD_BOOT_HEADER_VERSION := 0
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_HASH_TYPE := sha1
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
# Kernel
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 1671031022
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 167103102
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"

BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_SDCARD_ON_DATA := true

# Partitions (File systems)
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
#TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := mt6580

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 99.99.99

#PRODUCT_SOONG_NAMESPACES += vendor/zechin/agpt05

TW_SKIP_COMPATIBILITY_CHECK := true
TW_SUPPORT_INPUT_AIDL_HAPTICS := false
TW_THEME := portrait_mdpi
TW_DEFAULT_BRIGHTNESS := 120
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file
TW_MAX_BRIGHTNESS := 255
TW_EXCLUDE_SUPERSU := true
TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
TW_INCLUDE_CRYPTO := true
TW_CRYPTO_FS_TYPE := "ext4"
TW_CRYPTO_REAL_BLKDEV := "/dev/block/platform/mtk-msdc.0/11120000.msdc0/by-name/userdata"
TW_CRYPTO_MNT_POINT := "/data"
TW_CRYPTO_FS_OPTIONS := "nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered"
TW_EXTRA_LANGUAGES := false
TW_DEFAULT_LANGUAGE := en
TW_USE_INPUT_EVENTS := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_TIMEOUT := true
TW_USE_TOOLBOX := true
TW_NO_FASTBOOT_BOOT := false
TW_NO_HAPTICS := true
TW_EXCLUDE_TWRPAPP := true
TW_NO_BATT_PERCENT := false
TW_NO_USB_STORAGE := false
TW_HAS_MTP := false

TW_NO_EXFAT_FUSE := false
TW_EXCLUDE_BASH := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_LSOF := false
TW_EXCLUDE_LZMA := false
TW_EXCLUDE_SED := true
TW_EXCLUDE_TAR := false
TW_NO_BZIP2 := true
