#
# Copyright (C) 2023 The Android Open Source Project
# Copyright (C) 2023 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/h2/mdtab0801
TARGET_BUILD_64BIT := false
TARGET_BUILD_32BIT := true
# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
TARGET_ARCH            := arm
TARGET_ARCH_VARIANT    := armv7-a
TARGET_CPU_VARIANT     := generic
TARGET_CPU_ABI         := armeabi-v7a
TARGET_CPU_ABI2  := armeabi
TARGET_CPU_ABI_LIST    := armeabi-v7a
TARGET_2ND_ARCH :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_VARIANT :=
TARGET_2ND_CPU_VARIANT_RUNTIME :=

TARGET_SUPPORTS_64_BIT_APPS := false
TARGET_IS_64_BIT := false
TARGET_USES_64_BIT_BINDER := false
AB_OTA_UPDATER := false

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6765
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 213

# Boot Image
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x07880000
BOARD_RAMDISK_OFFSET := 0x11b00000
BOARD_KERNEL_SECOND_OFFSET := 0x00f00000
BOARD_BOOT_HEADER_VERSION := 1
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_HASH_TYPE := sha1
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
TARGET_KERNEL_CONFIG := $(DEVICE_PATH)/md0801_defconfig
# Kernel
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo
endif

# Partitions
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_VENDORIMAGE_PARTITION_SIZE := 838860800
BOARD_DTBOIMAGE_PARTITION_SIZE := 8388608
BOARD_VBMETAIMAGE_PARTITION_SIZE := 8388608
BOARD_USES_REMOUNT := true
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file
TARGET_DISABLE_TRIPLE_BUFFERING := false
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := \"/sys/class/leds/lcd-backlight/brightness\"
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := false
RECOVERY_SDCARD_ON_DATA := true

# Partitions (File systems)
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := mt6765

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 99.99.99
BOARD_AVB_ENABLE := true


# TWRP Configuration
TW_THEME := portrait_mdpi
DEVICE_SCREEN_WIDTH := 800
DEVICE_SCREEN_HEIGHT := 1280
TW_OEM_BUILD := true
RECOVERY_TOUCHSCREEN_SWAP_XY := true
RECOVERY_TOUCHSCREEN_FLIP_Y := true
TW_EXTRA_LANGUAGES := false
TW_USE_INPUT_EVENTS := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_TIMEOUT := true
TW_USE_TOOLBOX := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_APEX := true
TW_NO_FASTBOOT_BOOT := true
TW_NO_HAPTICS := true
TW_NO_CPU_TEMP := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_LSOF := true
TW_EXCLUDE_LZMA := true
TW_EXCLUDE_SED := true
TW_EXCLUDE_TAR := true
TW_INCLUDE_REPACKTOOLS := false
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_LPDUMP := true
TW_EXCLUDE_CRYPTO := true
TW_EXCLUDE_LOGCAT := true
TW_EXCLUDE_FB2PNG := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_LPTOOLS := true
TW_EXCLUDE_SU := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
TW_EXCLUDE_MTP := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_NO_BZIP2 := true
TW_NO_BATT_PERCENT := false
TW_NO_USB_STORAGE := true
TW_HAS_MTP := false
TW_EXCLUDE_AWK := true
TW_NO_EXFAT_FUSE := true
TW_EXCLUDE_GZIP := false
TW_EXCLUDE_XZ := true
